import json

P = 'conformance/golden-provenance-allowlist.json'
d = json.load(open(P))

UPDATES = {
    'conformance/script-size-baseline.json': {
        'sha256': '844432133133be29e7bed30994492e62abead3c1aae95c0e3d82503d22bd69c6',
        'verified-against': 'second-implementation',
        'reason': (
            "RE-DERIVED IN FULL on the post-#161 tree. This file documents one invariant "
            "-- every value is len(conformance/tests/<fixture>/expected-script.hex)/2 -- "
            "and 32 of its rows had stopped satisfying it.\n\n"
            "CAUSE, stated plainly because it is a regression on main and not something "
            "this branch introduced: #161 shrank the OP_PUSH_TX preimage-binding blob from "
            "760 to 428 bytes and correctly restamped every affected golden, but did not "
            "re-derive this file. Each stale row is therefore exactly 332 bytes too large "
            "per covenant method in its fixture (664 where a fixture has two). The "
            "regression check stayed green because those shrinks land under its 50 percent "
            "tolerance -- e.g. all-readonly-cleanstack 777 -> 445 is 43 percent -- so the "
            "guard went on protecting a figure no golden had produced. That is the same "
            "failure the nine rows corrected in #165 had, and the reason the tolerance band "
            "must not be mistaken for a correctness gate.\n\n"
            "Also in this change: the r1-k1-wallet row moves 959592 -> 959260 for the same "
            "reason (its spendR1 method calls checkPreimage, so it carries one blob), and "
            "that fixture's own goldens were regenerated by the runner rather than hand-"
            "edited.\n\n"
            "Re-audited at this hash: all 74 rows recomputed as len(expected-script.hex)/2 "
            "and all 74 match; script-size-check reports ok=74 warn=0 fail=0 missing=0. No "
            "fixture's BYTES were changed by this file -- it records sizes, and the sizes it "
            "now records are the ones the seven tiers actually produce (conformance runner "
            "74/74)."
        ),
        'reviewer': 'gh:icellan',
        'review-status': 'reviewed',
        'date': '2026-09-07',
    },
    'conformance/tests/r1-k1-wallet/expected-script.hex': {
        'sha256': '8a12c2be9712fe4a483dd7c7aaf99994a8a462ba27e81f2ea2903f82dd3dba84',
        'verified-against': 'differential-oracle',
        'reason': (
            "REGENERATED for the Any-S OP_PUSH_TX construction merged in #161: 959592 -> "
            "959260 bytes. R1K1Wallet is stateless but its spendR1 method calls "
            "checkPreimage explicitly, so it carries exactly one preimage-binding blob and "
            "loses exactly 760 - 428 = 332 bytes. Regenerated by conformance/runner "
            "--update-golden, never hand-edited; the ANF (expected-ir.json) is byte-"
            "identical to before, which is the expected shape for a change that moves only "
            "emitted bytes.\n\n"
            "Cross-checks, re-run on this tree rather than carried over: all SEVEN tiers "
            "reproduce these bytes from all NINE source formats (conformance runner 74/74, "
            "0 failed), and conformance/witnesses/real-crypto/r1-k1-wallet.json EXECUTES "
            "them through @bsv/sdk's real Spend engine -- an accept where the recovery key "
            "matches the constructor commitment and signs the genuine BIP-143 digest, and a "
            "crypto near-miss reject where a valid signature from the wrong key reaches the "
            "engine and fails the committed HASH160 guard. The reject is what keeps this "
            "non-vacuous."
        ),
        'reviewer': 'gh:icellan',
        'review-status': 'reviewed',
        'date': '2026-09-07',
    },
    'conformance/sdk-output/tests/r1-k1-wallet/expected-locking.hex': {
        'sha256': 'adfbcc9bbf6f880af182148cbcfe4d228487ca7ae57e32bd1cf45de87fdf6a7f',
        'verified-against': 'second-implementation',
        'reason': (
            "REGENERATED alongside the fixture golden above for the #161 Any-S blob: "
            "959632 -> 959300 bytes. The 40-byte gap from the fixture's 959260 is the two "
            "20-byte Addr constructor slots spliced by the SDK, so the arithmetic is "
            "checkable from the two numbers alone. Its input.json was regenerated first -- "
            "it embeds a frozen artifact, so refreshing only the expected hex would have "
            "compared new SDK output against a stale codePart.\n\n"
            "Cross-check: seven independently written deployment SDKs (TypeScript, Go, "
            "Rust, Python, Zig, Ruby, Java) each build the locking script from that "
            "artifact and are compared byte-for-byte against this pin and against each "
            "other by the required 'SDK Output Conformance' job. Scope note carried "
            "forward: this pin authorizes the bytes only. A 959300-byte output is still "
            "well above common 500 KB miner policy limits, as the example's README states."
        ),
        'reviewer': 'gh:icellan',
        'review-status': 'reviewed',
        'date': '2026-09-07',
    },
}

seen = set()
for e in d['entries']:
    u = UPDATES.get(e.get('path'))
    if u:
        e.update(u)
        seen.add(e['path'])
missing = set(UPDATES) - seen
assert not missing, f'entries not found: {missing}'

json.dump(d, open(P, 'w'), indent=2)
open(P, 'a').write('\n')
print('re-pinned', len(seen), 'entries')
